export interface Phase4SeedTopic {
  title: string;
  category: string;
  subcategory?: string;
  intendedDifficulty: "beginner" | "intermediate" | "advanced";
  reason: string;
  tags?: string[];
  includeAudio?: boolean;
}

/**
 * Curated seed list for Phase 4 completion.
 * These titles are intentionally chosen; we generate lesson/challenge/followups/trails/audio from them.
 */
export const PHASE_4_SEED_TOPICS: Phase4SeedTopic[] = [
  {
    title: "Why do octopuses have three hearts?",
    category: "Science",
    subcategory: "Marine biology",
    intendedDifficulty: "beginner",
    reason: "Iconic Kuriosa hook; strong across lesson + quiz + trails.",
    tags: ["octopus", "biology", "hearts"],
    includeAudio: true,
  },
  {
    title: "Why is lightning hotter than the sun?",
    category: "Science",
    subcategory: "Physics",
    intendedDifficulty: "beginner",
    reason: "High-curiosity comparison with clear explanation.",
    tags: ["lightning", "physics", "weather"],
    includeAudio: true,
  },
  {
    title: "Why does ice float on water?",
    category: "Science",
    subcategory: "Chemistry",
    intendedDifficulty: "beginner",
    reason: "Everyday phenomenon with strong aha payoff.",
    tags: ["water", "density"],
  },
  {
    title: "How did Roman concrete last so long?",
    category: "History",
    subcategory: "Engineering",
    intendedDifficulty: "intermediate",
    reason: "Ancient tech rabbit hole; bridges history + materials science.",
    tags: ["roman", "engineering"],
  },
  {
    title: "Why do we yawn—especially when others do?",
    category: "Psychology",
    subcategory: "Social cognition",
    intendedDifficulty: "beginner",
    reason: "Relatable social contagion; great follow-ups.",
    tags: ["yawning", "social"],
  },
  {
    title: "Why can’t we tickle ourselves?",
    category: "Psychology",
    subcategory: "Neuroscience",
    intendedDifficulty: "beginner",
    reason: "Fun hook; prediction and perception explained simply.",
    tags: ["brain", "prediction"],
  },
  {
    title: "How do bees make honey?",
    category: "Biology",
    subcategory: "Insects",
    intendedDifficulty: "beginner",
    reason: "Charming process; easy to narrate.",
    tags: ["bees", "honey"],
    includeAudio: true,
  },
  {
    title: "How do spiders walk on walls?",
    category: "Biology",
    subcategory: "Biomechanics",
    intendedDifficulty: "beginner",
    reason: "Clickable; physics + biology in one.",
    tags: ["spiders", "adhesion"],
  },
  {
    title: "Why do cats purr?",
    category: "Biology",
    subcategory: "Animal behavior",
    intendedDifficulty: "beginner",
    reason: "Popular and nuanced; multiple hypotheses.",
    tags: ["cats", "behavior"],
  },
  {
    title: "What makes a volcano “sleep” for centuries?",
    category: "Science",
    subcategory: "Geology",
    intendedDifficulty: "intermediate",
    reason: "Big wonder; introduces timescales and systems.",
    tags: ["volcano", "geology"],
  },
  {
    title: "What is the “dark side” of the Moon, really?",
    category: "Space",
    subcategory: "Astronomy",
    intendedDifficulty: "beginner",
    reason: "Misconception-busting; great trails to tides and orbits.",
    tags: ["moon", "space"],
  },
  {
    title: "How do we know the universe is expanding?",
    category: "Space",
    subcategory: "Cosmology",
    intendedDifficulty: "intermediate",
    reason: "Big idea grounded in evidence; builds trust.",
    tags: ["universe", "cosmology"],
  },
  {
    title: "Why do astronauts grow taller in space?",
    category: "Space",
    subcategory: "Human body",
    intendedDifficulty: "beginner",
    reason: "Visceral microgravity effect; simple physiology.",
    tags: ["astronauts", "microgravity"],
  },
  {
    title: "What happens if you fall into a black hole (in plain language)?",
    category: "Space",
    subcategory: "Relativity",
    intendedDifficulty: "intermediate",
    reason: "High curiosity; careful tone and clarity.",
    tags: ["black-holes", "relativity"],
  },
  {
    title: "Why do computers use binary?",
    category: "Technology",
    subcategory: "Computing basics",
    intendedDifficulty: "beginner",
    reason: "Foundational; sets up tech trails.",
    tags: ["binary", "computers"],
  },
  {
    title: "What is a “bug” in software—where did the name come from?",
    category: "Technology",
    subcategory: "History of computing",
    intendedDifficulty: "beginner",
    reason: "Story hook; approachable.",
    tags: ["software", "history"],
  },
  {
    title: "How does GPS know where you are?",
    category: "Technology",
    subcategory: "Signals",
    intendedDifficulty: "intermediate",
    reason: "Real-world relevance; physics without heavy math.",
    tags: ["gps", "satellites"],
  },
  {
    title: "Why do batteries wear out?",
    category: "Technology",
    subcategory: "Energy storage",
    intendedDifficulty: "intermediate",
    reason: "Common pain point; chemistry explained cleanly.",
    tags: ["batteries", "chemistry"],
  },
  {
    title: "Why do markets sometimes crash “for no reason”?",
    category: "Finance / Economics",
    subcategory: "Market dynamics",
    intendedDifficulty: "intermediate",
    reason: "Important concept; behavioral + liquidity.",
    tags: ["markets", "risk"],
  },
  {
    title: "What is inflation in one story (not a chart)?",
    category: "Finance / Economics",
    subcategory: "Money",
    intendedDifficulty: "beginner",
    reason: "Core concept; beginner-friendly framing.",
    tags: ["inflation", "money"],
  },
  {
    title: "Why do people value gold?",
    category: "Finance / Economics",
    subcategory: "Money history",
    intendedDifficulty: "beginner",
    reason: "Crosses culture + economics; strong trails.",
    tags: ["gold", "history"],
  },
  {
    title: "Can you step into the same river twice?",
    category: "Philosophy",
    subcategory: "Identity & change",
    intendedDifficulty: "intermediate",
    reason: "Classic thought; encourages follow-ups.",
    tags: ["change", "identity"],
  },
  {
    title: "What is a paradox, and why do they matter?",
    category: "Philosophy",
    subcategory: "Logic",
    intendedDifficulty: "beginner",
    reason: "Builds reasoning muscles; aligns with challenge style.",
    tags: ["paradox", "logic"],
  },
  {
    title: "Why do we remember embarrassing moments so vividly?",
    category: "Psychology",
    subcategory: "Memory",
    intendedDifficulty: "beginner",
    reason: "Relatable; strong follow-ups.",
    tags: ["memory", "emotion"],
  },
  {
    title: "Why do whales sing?",
    category: "Biology",
    subcategory: "Animal communication",
    intendedDifficulty: "beginner",
    reason: "Beautiful audio opportunity; wonder-forward.",
    tags: ["whales", "sound"],
    includeAudio: true,
  },
  {
    title: "How do trees “talk” to each other?",
    category: "Biology",
    subcategory: "Ecology",
    intendedDifficulty: "intermediate",
    reason: "Popular science with nuance; strong trails.",
    tags: ["trees", "fungi"],
  },
  {
    title: "Why do some languages have “untranslatable” words?",
    category: "Culture",
    subcategory: "Linguistics",
    intendedDifficulty: "intermediate",
    reason: "Human curiosity; excellent rabbit holes.",
    tags: ["language", "culture"],
  },
  {
    title: "Why did the Library of Alexandria matter so much?",
    category: "History",
    subcategory: "Knowledge systems",
    intendedDifficulty: "intermediate",
    reason: "History of ideas; strong relevance.",
    tags: ["alexandria", "books"],
  },
];

